version: "3"
services:
  linkchecker:
    image: ghcr.io/webdimension/linkchecker:latest
    container_name: ${PROJECT_NAME}_linkchecker
    volumes:
      - ${DIR_PATH}/output:/workspace/output
      - ${DIR_PATH}/src:/workspace/src
    working_dir: /workspace/src
    entrypoint: "/bin/sh -c './linkchecker.sh'"